#!/usr/bin/env bash

RECIP="$1"
SUBJECT="$2"
NOTE="note_$(date +%m-%d-%Y)"

vim "/tmp/${NOTE}"

wait $!

echo "Email created $(date)"

read -p "would you like to continue?: " RESP

if [[ "$RESP" =~ (y|Y|yes) ]]; then
    python3 emailer.py "$RECIP" "$SUBJECT" "$(cat "/tmp/$NOTE")" 
else
    rm $NOTE
    exit
fi
